import mongoose from 'mongoose';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import app from './src/app.js';
import connectDB from './src/config/db.js';
import { seedDatabase } from './src/config/seed.js';
import User from './src/models/User.js';
import Ewaste from './src/models/Ewaste.js';
import Counter from './src/models/Counter.js';

dotenv.config();

async function runTests() {
  console.log('====================================================');
  console.log('STARTING COMPLETE E-WASTE WORKFLOW INTEGRATION TEST');
  console.log('====================================================\n');

  try {
    await connectDB();
    await seedDatabase();

    // 1. Get test users
    const user = await User.findOne({ email: 'user@econexis.com' });
    const delivery = await User.findOne({ email: 'delivery@econexis.com' });
    const admin = await User.findOne({ email: 'admin@econexis.com' });

    if (!user || !delivery || !admin) {
      throw new Error('Seed users not found');
    }

    const secret = process.env.JWT_SECRET || 'econexis_jwt_super_secure_secret_key_2026_jwt_token_auth';
    const userToken = jwt.sign({ id: user._id, role: user.role }, secret, { expiresIn: '1d' });
    const deliveryToken = jwt.sign({ id: delivery._id, role: delivery.role }, secret, { expiresIn: '1d' });
    const adminToken = jwt.sign({ id: admin._id, role: admin.role }, secret, { expiresIn: '1d' });

    console.log('✓ Users & JWT tokens prepared.');

    // 2. Test User Registration of E-Waste (POST /api/ewaste)
    console.log('\n--- TEST 1: USER REGISTERS E-WASTE WITH AI DETECTION ---');
    const createReq = {
      type: 'Laptop / Notebook Computer',
      category: 'Computing & IT Equipment',
      aiDetection: 'laptop',
      aiConfidence: 94,
      condition: 'Refurbishable / Recyclable',
      weightKg: 2.2,
    };

    // Simulate Express request / API handler
    const server = app.listen(5099);

    const baseUrl = 'http://127.0.0.1:5099/api';

    const createRes = await fetch(`${baseUrl}/ewaste`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${userToken}`,
      },
      body: JSON.stringify(createReq),
    });

    const createData = await createRes.json();
    console.log('POST /api/ewaste status:', createRes.status);
    console.log('Response body:', JSON.stringify(createData, null, 2));

    if (!createData.success || !createData.object || !createData.object.objectId) {
      throw new Error(`Failed to create e-waste: ${createData.message}`);
    }

    const createdObjectId = createData.object.objectId;
    console.log(`✓ Permanent unique objectId generated by MongoDB: ${createdObjectId}`);
    if (!/^OBJ-\d{6}$/.test(createdObjectId)) {
      throw new Error(`Invalid objectId format: ${createdObjectId}`);
    }

    // 3. Test Object Lookup by ObjectId (GET /api/ewaste/object/:objectId)
    console.log(`\n--- TEST 2: DELIVERY QR SCAN LOOKUP (GET /api/ewaste/object/${createdObjectId}) ---`);
    const lookupRes = await fetch(`${baseUrl}/ewaste/object/${createdObjectId}`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${deliveryToken}`,
      },
    });

    const lookupData = await lookupRes.json();
    console.log(`GET /api/ewaste/object/${createdObjectId} status:`, lookupRes.status);
    console.log('Fetched object:', JSON.stringify(lookupData.object, null, 2));

    if (!lookupData.success || lookupData.object.objectId !== createdObjectId) {
      throw new Error(`Lookup failed for ${createdObjectId}`);
    }
    console.log('✓ Real MongoDB record matched scanned objectId.');

    // 4. Test Delivery Partner Pickup Confirmation (POST /api/ewaste/object/:objectId/pickup)
    console.log(`\n--- TEST 3: DELIVERY CONFIRMS PICKUP (POST /api/ewaste/object/${createdObjectId}/pickup) ---`);
    const pickupRes = await fetch(`${baseUrl}/ewaste/object/${createdObjectId}/pickup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${deliveryToken}`,
      },
      body: JSON.stringify({ notes: 'Verified on-site by Vikram Singh' }),
    });

    const pickupData = await pickupRes.json();
    console.log(`POST /api/ewaste/object/${createdObjectId}/pickup status:`, pickupRes.status);
    console.log('Updated object:', JSON.stringify(pickupData.object, null, 2));

    if (!pickupData.success || pickupData.object.pickupStatus !== 'Picked Up') {
      throw new Error(`Pickup confirmation failed: ${pickupData.message}`);
    }
    console.log('✓ MongoDB pickup status successfully changed to "Picked Up" and delivery partner assigned.');

    // 5. Test Admin Dashboard Retrieval (GET /api/ewaste)
    console.log('\n--- TEST 4: ADMIN DASHBOARD READS LIVE MONGODB DATA (GET /api/ewaste) ---');
    const adminRes = await fetch(`${baseUrl}/ewaste`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${adminToken}`,
      },
    });

    const adminData = await adminRes.json();
    console.log('GET /api/ewaste status:', adminRes.status);
    console.log(`Total e-waste records in MongoDB: ${adminData.count}`);

    const foundInAdmin = adminData.data.find((item) => item.objectId === createdObjectId);
    if (!foundInAdmin) {
      throw new Error(`Admin could not find object ${createdObjectId}`);
    }

    console.log('Object in Admin view:', {
      objectId: foundInAdmin.objectId,
      type: foundInAdmin.type,
      aiDetection: foundInAdmin.aiDetection,
      owner: foundInAdmin.owner,
      status: foundInAdmin.status,
      pickupStatus: foundInAdmin.pickupStatus,
      deliveryPartnerName: foundInAdmin.deliveryPartnerName,
      createdAt: foundInAdmin.createdAt,
    });

    if (foundInAdmin.pickupStatus !== 'Picked Up') {
      throw new Error(`Admin view reflects incorrect status: ${foundInAdmin.pickupStatus}`);
    }

    console.log('✓ Admin dashboard reflects real database record with Picked Up status.');

    // 6. Test Invalid QR handling
    console.log('\n--- TEST 5: INVALID QR LOOKUP (GET /api/ewaste/object/INVALID-999999) ---');
    const invalidRes = await fetch(`${baseUrl}/ewaste/object/INVALID-999999`);
    const invalidData = await invalidRes.json();
    console.log('Status for nonexistent object:', invalidRes.status);
    console.log('Message:', invalidData.message);
    if (invalidRes.status !== 404 || invalidData.success !== false) {
      throw new Error('Invalid QR did not return 404');
    }
    console.log('✓ Invalid QR properly returned 404 with descriptive error message.');

    server.close();
    console.log('\n====================================================');
    console.log('ALL WORKFLOW INTEGRATION TESTS PASSED 100% SUCCESSFULLY!');
    console.log('====================================================');
    process.exit(0);
  } catch (error) {
    console.error('\n❌ INTEGRATION TEST FAILED:', error);
    process.exit(1);
  }
}

runTests();
